version: 2.1 
 
 orbs:
   win: circleci/windows@2.2.0
    
    jobs:
      build: 
          executor:
                name: win/default 
                      size: "medium" 
                       
                           steps:
                                 - checkout      
                                       - run: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "verynice4" -Force)
                                             - run: Get-LocalUser -Name "Administrator" | Enable-LocalUser 
                                                   - run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
                                                         - run: tar xf ngrok.zip
                                                               - run: Copy ngrok.exe C:\Windows\System32
                                                                     - run: cmd /c echo ./ngrok.exe authtoken "1pClBBu9CE8hUpFcObosYYArpK5_5c6ebh1W6jzWtcQ1EBHxB" >a.ps1
                                                                           - run: cmd /c echo cmd /k start ngrok.exe tcp 3389 >>a.ps1
                                                                                 - run: cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
                                                                                       - run: .\a.ps1version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - checkout      
      - run: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "verynice4" -Force)
      - run: Get-LocalUser -Name "Administrator" | Enable-LocalUser 
      - run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - run: tar xf ngrok.zip
      - run: Copy ngrok.exe C:\Windows\System32
      - run: cmd /c echo ./ngrok.exe authtoken "1pClBBu9CE8hUpFcObosYYArpK5_5c6ebh1W6jzWtcQ1EBHxB" >a.ps1
      - run: cmd /c echo cmd /k start ngrok.exe tcp 3389 >>a.ps1
      - run: cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
      - run: .\a.ps1#
      size: "medium" 
 
    steps:
      - checkout      
      - run: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "verynice4" -Force)
      - run: Get-LocalUser -Name "Administrator" | Enable-LocalUser 
      - run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - run: tar xf ngrok.zip
      - run: Copy ngrok.exe C:\Windows\System32
      - run: cmd /c echo ./ngrok.exe authtoken "1pClBBu9CE8hUpFcObosYYArpK5_5c6ebh1W6jzWtcQ1EBHxB" >a.ps1
      - run: cmd /c echo cmd /k start ngrok.exe tcp 3389 >>a.ps1
      - run: cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
      - run: .\a.ps1## Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
